name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send release to Discord
        run: |
          BODY=$(jq -r '.release.body' <<< '${{ toJson(github.event) }}')

          CHANGES=$(echo "$BODY" | awk '
            /<!-- DISCORD_START -->/{flag=1; next}
            /<!-- DISCORD_END -->/{flag=0}
            flag
          ')

          if [ -z "$CHANGES" ]; then
            CHANGES="No changelog provided."
          fi

          PAYLOAD=$(jq -n \
            --arg title "${{ github.event.release.name }}" \
            --arg version "${{ github.event.release.tag_name }}" \
            --arg url "${{ github.event.release.html_url }}" \
            --arg content "$CHANGES" \
            '{
              content: "<@&1519341297188470874>",
              allowed_mentions: {
                roles: ["1519341297188470874"]
              },

              embeds: [
                {
                  title: ("🚀 \($title)"),
                  url: $url,
                  color: 5793266,

                  thumbnail: {
                    url: "https://cdn.discordapp.com/attachments/1452039397435244677/1458169510447153255/ChatGPT_Image_20_._2025_._17_38_56_1.png?ex=6a3e1fee&is=6a3cce6e&hm=defdd5d62ba2d6050a22f137211a6024374a15da995d9ab0dbb69271bdb990bb"
                  },

                  fields: [
                    {
                      name: "📦 Version",
                      value: ("`\($version)`"),
                      inline: true
                    },
                    {
                      name: "🔗 Release",
                      value: ("[Open on GitHub](\($url))"),
                      inline: true
                    }
                  ],

                  description: ("## 🆕 Changelog\n\n" + $content),

                  footer: {
                    text: "Core Release System"
                  }
                }
              ]
            }')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$PAYLOAD" \
          ${{ secrets.DISCORD_WEBHOOK }}
