name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send release to Discord
        shell: bash
        run: |
          set -e

          BODY='${{ toJson(github.event.release.body) }}'
          BODY=$(echo "$BODY" | jq -r '.')

          CHANGES=$(echo "$BODY" | awk '
            /<!-- DISCORD_START -->/{flag=1; next}
            /<!-- DISCORD_END -->/{flag=0}
            flag
          ')

          if [ -z "$CHANGES" ]; then
            CHANGES="No changelog provided."
          fi

          # защита от Discord лимитов
          CHANGES=$(echo "$CHANGES" | head -c 3500)

          CONTENT=$(jq -Rs . <<< "$CHANGES")

          PAYLOAD=$(jq -n \
            --arg title "${{ github.event.release.name }}" \
            --arg version "${{ github.event.release.tag_name }}" \
            --arg url "${{ github.event.release.html_url }}" \
            --argjson content "$CONTENT" \
            '{
              content: "<@&1519341297188470874>",
              allowed_mentions: {
                parse: [],
                roles: ["1519341297188470874"]
              },
              embeds: [
                {
                  title: ("🚀 " + $title),
                  url: $url,
                  color: 5793266,

                  thumbnail: {
                    url: "https://cdn.discordapp.com/attachments/1452039397435244677/1458169510447153255/ChatGPT_Image_20_._2025_._17_38_56_1.png"
                  },

                  fields: [
                    {
                      name: "📦 Version",
                      value: ("`" + $version + "`"),
                      inline: true
                    },
                    {
                      name: "🔗 Release",
                      value: ("[Open on GitHub](" + $url + ")"),
                      inline: true
                    }
                  ],

                  description: ("## 🆕 Changelog\n\n" + $content),

                  footer: {
                    text: "Core Release System"
                  }
                }
              ]
            }')

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "$PAYLOAD" \
            "${{ secrets.DISCORD_WEBHOOK }}"
