name: Webhook Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Send test message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"🔥 MANUAL GITHUB ACTION TEST"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
