- name: Discord test
  run: |
    response=$(curl -s -w "%{http_code}" \
      -H "Content-Type: application/json" \
      -X POST \
      -d '{"content":"🔥 TEST FROM GITHUB ACTIONS"}' \
      ${{ secrets.DISCORD_WEBHOOK }})

    echo "RESPONSE: $response"
